//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter.Web {
    
    
    public partial class Default {
        
        /// <summary>
        /// LoginStatus1 control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LoginStatus LoginStatus1;
    }
}
