//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCenter.Web.Account {
    
    
    public partial class Login {
        
        protected global::System.Web.UI.WebControls.ValidationSummary vs;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        
        protected global::System.Web.UI.WebControls.Button btnLogin;
        
        protected global::System.Web.UI.WebControls.Label lblError;
    }
}
